version: '2'
services:
  db:
    image: postgres
    container_name: cognoma-core-service-postgres
  core:
    build: .
    container_name: cognoma-core-service
    command: bash -c "python manage.py makemigrations genes && python manage.py makemigrations organisms && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: cognoma-nginx
    ports:
      - "8080:80"
