# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sample_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('entrezid', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('chromosome', models.CharField(max_length=25, null=True)),
                ('gene_type', models.CharField(max_length=25)),
                ('synonyms', models.TextField(null=True)),
                ('aliases', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cognoma_genes',
            },
        ),
        migrations.AlterField(
            model_name='classifier',
            name='genes',
            field=models.ManyToManyField(to='api.Gene'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='api.Gene'),
        ),
    ]
