# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cognoma_genes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutation',
            name='status',
        ),
    ]
